repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      # Black doesn't support < Python 3.6 version
      # Also, pre-commit create a new venv just for black